### ISSUE TITLE
Extend IUnleash interface with additional GetVariants method implementation 

### ISSUE THREAD

**Issue by olehfitsyk** [Unleash/unleash-client-dotnet#92]
**Is your feature request related to a problem? Please describe.**
I'm building a wrapper around the `IUnleash` interface to be able to use DI and scoped `IUnleashContextProvider`. The idea of it is quite simple. Every time someone uses the `IUnleash` interface and does not pass its own `UnleashContext` in a method, I automatically pass `UnleashContext` from DI. Most of the methods have a version where you can pass `UnleashContext` as a parameter. But there's no such option for the `GetVariants` method that uses `IsEnabled(toggleName)` under the hood and can use `UnleashContext`.

**Describe the solution you'd like**
From a consistency point of view, it makes sense to introduce `IEnumerable<VariantDefinition> GetVariants(string toggleName, UnleashContext context);`. It won't break existing integrations so shouldn't be considered a breaking change. If you guys approve it, I can gladly assist with PR.

**Additional context**
I'm trying to do something very similar to [this ](https://github.com/Unleash/unleash-client-dotnet/issues/37#issuecomment-542857588) component-wise.

**Comment by FredrikOseberg** [comment]
Hey @olehfitsyk . I'll note this as a discussion item in the standup tomorrow. Let me get back to you shortly on this.

**Comment by FredrikOseberg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github Issue: Extend IUnleash interface](https://trello.com/c/rTGvMDaf/1139-github-issue-extend-iunleash-interface)

**Comment by sighphyre** [comment]
@olehfitsyk We've chatted internally about this one, so the method in question is a bit strange, it's not present in any of our other SDKs and we don't have an intentional use case for it as part of the public API (consumers should probably just rely on getVariant, rather than getVariants). From the commit history, it seems this was added to mirror the Java SDK (it turns out this has a very different usage in the Java SDK). We have no plans to remove the method in question but we may mark it as deprecated at some point.

All that being said, if you're building a wrapper to simplify your use cases then it makes perfect sense to do the changes you're proposing and I think it's a great idea! If you're up for making a PR that would be amazing!
